const COMMANDS = {
  DATABASES: 'SHOW DATABASES;',
  FILE_FORMATS: 'SHOW FILE FORMATS;',
  FUNCTIONS: 'SHOW FUNCTIONS;',
  GRANTS: 'SHOW GRANTS;',
  INTEGRATIONS: 'SHOW INTEGRATIONS;',
  MANAGED_ACCOUNTS: 'SHOW MANAGED ACCOUNTS;',
  PIPES: 'SHOW PIPES;',
  PROCEDURES: 'SHOW PROCEDURES;',
  REGIONS: 'SHOW REGIONS;',
  SCHEMAS: 'SHOW SCHEMAS;',
  SHARES: 'SHOW SHARES;',
  STAGES: 'SHOW STAGES;',
  STREAMS: 'SHOW STREAMS;',
  TABLES: 'SHOW TABLES;',
  TASKS: 'SHOW TASKS;',
  // Why does SHOW USERS require MANAGE GRANTS????
  USERS: 'SHOW USERS;',
  VIEWS: 'SHOW VIEWS;',
  WAREHOUSES: 'SHOW WAREHOUSES;',
} as const;

export default COMMANDS;
