name: Build
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - id: setup-node
        name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check out code repository source code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Run build
        run: yarn build
